server {
    listen 80;

    # Frontend
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Backend via INTERNAL LOAD BALANCER
    location /api/ {
        proxy_pass http://<INTERNAL-ALB-DNS>/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
#/etc/nginx/conf.d/app.conf
